name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build job
  build:
    # Name of the job
    name: Build
    # The type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Add env file
        run: echo "${{ secrets.DOTENV }}" > .env
      - name: Install NPM Dependencies
        run: npm install --prefix ./client
      - name: Build
        run: npm run build --prefix ./client
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: client/build

  # Deploy job
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_FE_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'production'
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
  