on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  # Build job
  build:
    # Name of the job
    name: Build
    # The type of machine to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 21
        uses: actions/setup-node@v2
        with:
          node-version: 21.x
      - name: Install NPM Dependencies
        run: npm install --prefic ./client
      - name: Build
        run: npm run build --prefix ./client
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./client/dist

  # Deploy job
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./client/dist
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          publish_dir: ./client/dist
  