name: Test

on:
  push:
    branches:
      - dev
      - "**/*_test"
  pull_request:
    branches:
      - "**/*_test"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM Dependencies
        run: npm install react-fade-in@latest react-reveal@latest --save-dev --prefix ./client
      - name: Test
        run: npm run test --prefix ./client
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: 08Arno30/enhanced-email-automated-app